version: '3.8'

services:
#  backend:
#    build: ./backend
#    ports:
#      - "5000:5000"
#    env_file:
#      - ./.env
#    depends_on:
#      - db
#    networks:
#      - app-network
#
#  frontend:
#    build: ./frontend
#    ports:
#      - "3000:3000"
#    env_file:
#      - ./.env
#    networks:
#      - app-network

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: handly_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
